- name: create-rds-intance
  hosts: "{{ variable_host }}"
  # hosts: db
  connection: local
  gather_facts : false

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
 
  tasks:
    - name: Create snapshot
      community.aws.rds_instance_snapshot:
        db_instance_identifier: "{{ db_instance_id }}"
        db_snapshot_identifier: "{{ db_instance_id }}-preupgrade"
