- name: upgrade-rds-intance
  hosts:  "{{ variable_host }}"
  connection: local
  gather_facts : false

  tasks:

    #    - name: script run
    # ansible.builtin.script: /home/sunny/Projects/terraform/ansible_aws/script.sh
    # register: command_output

    # - set_fact:
    #   test1: "{{ command_output.stdout | trim }}"

    - name: Upgrade db instance
      community.aws.rds_instance:
        db_instance_identifier: "{{ db_instance_id }}"
        engine_version: "{{ new_version }}"
        apply_immediately: yes
